apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: woorkroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: 786998285740.dkr.ecr.us-east-1.amazonaws.com/woorkroom-authorization:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: woorkroom-config
            - secretRef:
                name: woorkroom-secrets
